FROM golang:1.24-alpine

WORKDIR /app

RUN apk --no-cache add ca-certificates tzdata \
	&& cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime \
	&& echo "Asia/Tokyo" > /etc/timezone \
	&& apk del tzdata

COPY ../go.mod ../go.sum ./
RUN go mod download

COPY . .

RUN go install github.com/air-verse/air@latest

RUN go build -o /ecs cmd/ecs/main.go

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]