FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY ../go.mod ../go.sum ./
RUN go mod download

COPY . .

RUN go install github.com/air-verse/air@latest

RUN go build -o /lambda cmd/lambda/main.go

FROM public.ecr.aws/lambda/provided:al2

COPY --from=builder /lambda /var/task/

CMD ["main"]
