FROM golang:1.24-alpine

WORKDIR /app

COPY ../go.mod ../go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o /lambda cmd/lambda/main.go

FROM public.ecr.aws/lambda/provided:al2

COPY --from=builder /lambda /var/task/

CMD ["main"]
